# this file is *not* meant to cover or endorse the use of travis, but rather to
# help confirm pull requests to this project.

language: python


matrix:
  include:
    - os: linux
      python: 3.7
      env: REPO=https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
    - os: linux
      python: 3.6
      env: REPO=https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
    - os: osx
      python: 3.7
      env: REPO=https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
    - os: osx
      python: 3.6
      env: REPO=https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh

wget https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O ~/miniconda.sh

install:
  - wget "$REPO" -O ~/miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda install conda-build
  - conda update -q conda
  - conda update -n root conda-build
  - conda config --set anaconda_upload no
  - conda install python="$TRAVIS_PYTHON_VERSION"
  - conda install cython numpy


script:
  - python setup.py install
  - python -c "print('im here');"
  - python -c "import sample as sp; print(sp.__file__)"

notifications:
  email: false
