# this file is *not* meant to cover or endorse the use of travis, but rather to
# help confirm pull requests to this project.

language: python


matrix:
  include:
    - os: linux
      python: 3.7
      env: =py37
    - os: linux
      python: 3.8
      env: TOXENV=py38

install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "3.7-dev" ]]; then export VADD="py37"; else export VADD="py36";  fi
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
    -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda install conda-build
  - conda update-q conda
  - conda update -n root conda-build
  - conda config --set anaconda_upload no
  - conda create -n travisconda python="$TRAVIS_PYTHON_VERSION"
  - conda activate travisconda
  - conda install cython numpy


script:
  - python setup.py build_ext --inplace
  - python -c \"print('im here'); import npyx; print(npyx.__version)\"

notifications:
  email: false
